### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/accessibility_map#1]
java.lang.NullPointerException
at org.fruct.oss.accessibilitymap.ActivityMain$7.onDismiss(ActivityMain.java:224)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1235)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4513)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:974)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:741)
at dalvik.system.NativeStart.main(Native Method)

**Comment by seekerk** [comment]
Опубликовано
